spring:
  application:
    name: BMS Monolith
  datasource:
    url: jdbc:mysql://localhost:3306/bms
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true
server:
  servlet:
    context-path: /api/v1
app:
  auth:
    jwt:
      secret-key: ${JWT_SECRET_KEY:ZmxhbWVyb2xsc3RvcHBlZGNyZWFtY29sbGVjdGZhbGxzb2xkaWVydG9uZWdpdmVua24=}
      expiration-in-ms: ${JWT_EXPIRATION_IN_MS:50000}